// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from "path";
import * as lambda from "aws-cdk-lib/aws-lambda";
import { Construct } from "constructs";

/**
 * Props for GetUserFunction
 */
export interface GetUserFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/server/lambdas/User/get-user.
 */
export class GetUserFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: GetUserFunctionProps) {
    super(scope, id, {
      description: "src/server/lambdas/User/get-user.lambda.ts",
      ...props,
      runtime: new lambda.Runtime("nodejs14.x", lambda.RuntimeFamily.NODEJS),
      handler: "index.handler",
      code: lambda.Code.fromAsset(path.join(__dirname, "../../../../assets/server/lambdas/User/get-user.lambda")),
    });
    this.addEnvironment("AWS_NODEJS_CONNECTION_REUSE_ENABLED", "1", { removeInEdge: true });
  }
}